# Generated by Django 5.1.6 on 2026-09-05 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('STALLED', 'Stalled deal'), ('DISCOUNT_ANOMALY', 'Discount anomaly'), ('DELIVERY_SLIPPAGE', 'Delivery slippage')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('message', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=14)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deal_alert',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DealHealthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stalled_days_threshold', models.IntegerField(default=7)),
                ('anomaly_multiplier', models.DecimalField(decimal_places=2, default=2, max_digits=4)),
                ('anomaly_min_quotes', models.IntegerField(default=3)),
                ('slippage_grace_days', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'deal_health_config',
            },
        ),
        migrations.CreateModel(
            name='RepDiscountStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quote_count', models.IntegerField(default=0)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
            ],
            options={
                'db_table': 'rep_discount_stat',
            },
        ),
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('NUDGE', 'Nudge rep'), ('ESCALATE', 'Escalate to manager')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert_action',
            },
        ),
    ]
