# Generated by Django 5.1.6 on 2026-09-05 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insights', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealalert',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='alertaction',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='insights.dealalert'),
        ),
        migrations.AddField(
            model_name='repdiscountstat',
            name='rep',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_stat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dealalert',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('quotation', 'alert_type'), name='unique_open_alert_per_quotation_type'),
        ),
    ]
