# Generated by Django 5.1.6 on 2026-09-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('band', models.CharField(choices=[('NONE', 'No approval needed'), ('MEDIUM', 'Sales Manager'), ('HIGH', 'Sales Manager then Finance')], max_length=10)),
                ('min_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('required_roles', models.JSONField(default=list)),
                ('sequence', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'approval_rule',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_worst', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('weight_blended', models.DecimalField(decimal_places=2, default=0.3, max_digits=4)),
                ('weight_order', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('cap_worst', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('cap_blended', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('cap_order', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('high_band_threshold', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
            ],
            options={
                'db_table': 'risk_config',
            },
        ),
        migrations.CreateModel(
            name='TierDiscountCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=10, unique=True)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'tier_discount_ceiling',
            },
        ),
        migrations.CreateModel(
            name='CategoryDiscountCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_ceiling', to='catalog.productcategory')),
            ],
            options={
                'db_table': 'category_discount_ceiling',
            },
        ),
    ]
