# Generated by Django 5.1.6 on 2026-09-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('is_backorder', models.BooleanField(default=False)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fulfillment_allocation',
            },
        ),
        migrations.CreateModel(
            name='FulfillmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Split suggested'), ('ACCEPTED', 'Split accepted'), ('OVERRIDDEN', 'Manually overridden'), ('PARTIALLY_SHIPPED', 'Partially shipped'), ('SHIPPED', 'Shipped'), ('BACKORDER', 'Backorder')], default='SUGGESTED', max_length=20)),
                ('estimated_shipments', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('consolidation_available', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fulfillment_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('quantity_reserved', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('reorder_quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stock_item',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta', models.IntegerField(help_text='Signed change to quantity_on_hand')),
                ('reason', models.CharField(choices=[('RESERVE', 'Reserved for order'), ('RELEASE', 'Reservation released'), ('SHIP', 'Shipped'), ('RESTOCK', 'Restocked'), ('ADJUST', 'Manual adjustment')], max_length=12)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_move',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('shipping_cost_weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('base_shipment_cost', models.DecimalField(decimal_places=2, default=30, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'warehouse',
                'ordering': ['shipping_cost_weight', 'name'],
            },
        ),
    ]
