# Generated by Django 5.1.6 on 2026-09-05 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('fulfillment', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillmentallocation',
            name='quotation_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='quotations.quotationline'),
        ),
        migrations.AddField(
            model_name='fulfillmentplan',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_plans', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='fulfillmentallocation',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fulfillment.fulfillmentplan'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='fulfillment.stockitem'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='fulfillment.warehouse'),
        ),
        migrations.AddField(
            model_name='fulfillmentallocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fulfillment.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('warehouse', 'product', 'variant')},
        ),
    ]
