# Generated by Django 5.1.6 on 2026-09-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='lead_time_days',
            field=models.IntegerField(default=3),
        ),
    ]
