# Generated by Django 5.1.6 on 2026-09-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_band', models.CharField(choices=[('NONE', 'No approval needed'), ('MEDIUM', 'Sales Manager'), ('HIGH', 'Sales Manager then Finance')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for revision'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=12)),
                ('reason', models.TextField(blank=True, help_text='Why this quote was flagged')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'approval_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.IntegerField()),
                ('role_required', models.CharField(choices=[('ADMIN', 'Admin'), ('SALES_REP', 'Sales Rep'), ('SALES_MANAGER', 'Sales Manager'), ('FINANCE', 'Finance / Operations'), ('CUSTOMER', 'Customer')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for revision'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=12)),
                ('decision_note', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'approval_step',
                'ordering': ['sequence'],
            },
        ),
    ]
