# Generated by Django 5.1.6 on 2026-09-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'invoice_line',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('APPLIED', 'Applied'), ('VOID', 'Void')], default='ISSUED', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='accounts.customer')),
            ],
            options={
                'db_table': 'credit_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('invoice_type', models.CharField(choices=[('ONE_TIME', 'One-time'), ('RECURRING', 'Recurring'), ('PRORATION', 'Proration')], default='ONE_TIME', max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Unpaid'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='OPEN', max_length=16)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.customer')),
            ],
            options={
                'db_table': 'invoice',
                'ordering': ['-issue_date', '-id'],
            },
        ),
    ]
