# Generated by Django 5.1.6 on 2026-09-05 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('negotiation', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationmessage',
            name='quotation_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quotations.quotationline'),
        ),
        migrations.AddField(
            model_name='negotiationrequest',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_requests', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='negotiationrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negotiationthread',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_thread', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='negotiationrequest',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='negotiation.negotiationthread'),
        ),
        migrations.AddField(
            model_name='negotiationmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='negotiation.negotiationthread'),
        ),
        migrations.AddField(
            model_name='portaltoken',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='portaltoken',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to='quotations.quotation'),
        ),
    ]
