# Generated by Django 5.1.6 on 2026-09-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequest',
            name='counter_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
