# Generated by Django 5.1.6 on 2026-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiation', '0003_negotiationrequest_counter_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationrequest',
            name='counter_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
