# Generated by Django 5.1.6 on 2026-09-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiation', '0004_alter_negotiationrequest_counter_discount_percent'),
        ('quotations', '0003_alter_quotationevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('MESSAGE', 'Message'), ('COUNTER_REQUEST', 'Customer counter-offer'), ('REP_COUNTER', 'Our counter-offer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Declined'), ('SENT', 'Quotation sent'), ('CONFIRMED', 'Confirmed by customer')], max_length=20)),
                ('author_type', models.CharField(max_length=10)),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(blank=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_events', to='quotations.quotation')),
                ('quotation_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotations.quotationline')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='negotiation.negotiationrequest')),
            ],
            options={
                'db_table': 'negotiation_event',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['quotation', 'created_at'], name='negotiation_quotati_4d88dc_idx')],
            },
        ),
    ]
