# Generated by Django 5.1.6 on 2026-09-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiation', '0007_settle_stranded_negotiations'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaltoken',
            name='terms_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
