# Generated by Django 5.1.6 on 2026-09-05 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('billing', '0001_initial'),
        ('catalog', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('interval', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=12)),
                ('proration_mode', models.CharField(choices=[('DAILY', 'Daily pro-rata'), ('NONE', 'No proration'), ('FULL_PERIOD', 'Charge full period')], default='DAILY', max_length=12)),
                ('cancellation_policy', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('END_OF_PERIOD', 'End of current period')], default='IMMEDIATE', max_length=16)),
                ('refund_mode', models.CharField(choices=[('PRORATED', 'Prorated refund'), ('NONE', 'No refund')], default='PRORATED', max_length=10)),
                ('bill_in_advance', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'recurring_plan',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=12)),
                ('start_date', models.DateField()),
                ('current_period_start', models.DateField()),
                ('current_period_end', models.DateField()),
                ('next_bill_date', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_effective_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.recurringplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='quotations.quotation')),
                ('quotation_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='quotations.quotationline')),
            ],
            options={
                'db_table': 'subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('QUANTITY_CHANGED', 'Quantity changed'), ('PLAN_CHANGED', 'Plan changed'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed'), ('CANCELLED', 'Cancelled'), ('RENEWED', 'Renewed')], max_length=20)),
                ('effective_date', models.DateField()),
                ('old_quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True)),
                ('new_quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True)),
                ('proration_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.creditnote')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.invoice')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'subscription_event',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
