# Generated by Django 5.1.6 on 2026-09-05 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('quotations', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recurring_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='subscriptions.recurringplan'),
        ),
        migrations.AddField(
            model_name='pricelistrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.productattribute'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory'),
        ),
        migrations.AddField(
            model_name='pricelistrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='catalog.productcategory'),
        ),
        migrations.AddField(
            model_name='productpairing',
            name='source_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_out', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productpairing',
            name='target_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_in', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='variants', to='catalog.productattributevalue'),
        ),
        migrations.AddField(
            model_name='upsellsuggestionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upsellsuggestionlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_logs', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='upsellsuggestionlog',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_logs', to='quotations.quotation'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='productpairing',
            unique_together={('source_product', 'target_product')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'sku_suffix')},
        ),
    ]
