# Generated by Django 5.1.6 on 2026-09-05 06:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('UNDER_NEGOTIATION', 'Under Negotiation'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('order_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('blended_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_band', models.CharField(choices=[('NONE', 'No approval needed'), ('MEDIUM', 'Sales Manager'), ('HIGH', 'Sales Manager then Finance')], default='NONE', max_length=10)),
                ('requires_approval', models.BooleanField(default=False)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='accounts.customer')),
                ('owner_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.pricelist')),
            ],
            options={
                'db_table': 'quotation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('LINE_ADDED', 'Line added'), ('LINE_UPDATED', 'Line updated'), ('LINE_REMOVED', 'Line removed'), ('DISCOUNT_CHANGED', 'Discount changed'), ('UPSELL_ADDED', 'Upsell added'), ('SUBMITTED', 'Submitted for approval'), ('AUTO_APPROVED', 'Auto-approved (within limits)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for revision'), ('SENT_TO_CUSTOMER', 'Sent to customer'), ('NEGOTIATION_OPENED', 'Negotiation opened'), ('COUNTER_RECEIVED', 'Counter-offer received'), ('COUNTER_ACCEPTED', 'Counter-offer accepted'), ('CONFIRMED', 'Confirmed'), ('NUDGED', 'Nudged'), ('ESCALATED', 'Escalated')], max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quotations.quotation')),
            ],
            options={
                'db_table': 'quotation_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_type', models.CharField(choices=[('ONE_TIME', 'One-time'), ('RECURRING', 'Recurring')], default='ONE_TIME', max_length=12)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('allowed_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_excess_points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('position', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.quotation')),
            ],
            options={
                'db_table': 'quotation_line',
                'ordering': ['position', 'id'],
            },
        ),
    ]
