# Generated by Django 5.1.6 on 2026-09-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('quotations', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='recurring_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscriptions.recurringplan'),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productvariant'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status'], name='quotation_status_09ff13_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['owner_rep', 'status'], name='quotation_owner_r_ca2912_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['last_activity_at'], name='quotation_last_ac_cbdc2b_idx'),
        ),
    ]
