# Generated by Django 5.1.6 on 2026-09-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('LINE_ADDED', 'Line added'), ('LINE_UPDATED', 'Line updated'), ('LINE_REMOVED', 'Line removed'), ('DISCOUNT_CHANGED', 'Discount changed'), ('UPSELL_ADDED', 'Upsell added'), ('DRAFT_SAVED', 'Draft saved'), ('SUBMITTED', 'Submitted for approval'), ('AUTO_APPROVED', 'Auto-approved (within limits)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for revision'), ('SENT_TO_CUSTOMER', 'Sent to customer'), ('NEGOTIATION_OPENED', 'Negotiation opened'), ('COUNTER_RECEIVED', 'Counter-offer received'), ('COUNTER_ACCEPTED', 'Counter-offer accepted'), ('CONFIRMED', 'Confirmed'), ('NUDGED', 'Nudged'), ('ESCALATED', 'Escalated')], max_length=24),
        ),
    ]
