# Generated by Django 5.1.6 on 2026-09-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_alter_quotationevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
