# Generated by Django 5.1.6 on 2026-09-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotation_customer_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='approved_terms_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
